
import { useState, useEffect } from 'react';
import MainLayout from '@/components/layout/MainLayout';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Dialog, DialogTrigger, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from '@/components/ui/dialog';
import { Form, FormField, FormItem, FormLabel, FormControl } from '@/components/ui/form';
import { Plus, Edit, Trash2 } from 'lucide-react';
import { useForm } from 'react-hook-form';
import { useToast } from '@/hooks/use-toast';
import { Route as RouteType } from '@/lib/types';

// Mock data
const mockRoutes: RouteType[] = [
  { id: '1', name: 'North Area' },
  { id: '2', name: 'South Area' },
  { id: '3', name: 'East Area' },
  { id: '4', name: 'West Area' },
  { id: '5', name: 'Central Area' },
];

export default function Routes() {
  const [routes, setRoutes] = useState<RouteType[]>([]);
  const [loading, setLoading] = useState(true);
  const [openDialog, setOpenDialog] = useState(false);
  const [editingRoute, setEditingRoute] = useState<RouteType | null>(null);
  const { toast } = useToast();
  
  const form = useForm<{ name: string }>({
    defaultValues: {
      name: '',
    },
  });
  
  useEffect(() => {
    // Simulate API call
    setTimeout(() => {
      setRoutes(mockRoutes);
      setLoading(false);
    }, 1000);
  }, []);
  
  useEffect(() => {
    if (editingRoute) {
      form.setValue('name', editingRoute.name);
    } else {
      form.reset();
    }
  }, [editingRoute, form]);
  
  const onSubmit = (data: { name: string }) => {
    if (editingRoute) {
      // Update existing route
      setRoutes(prev => 
        prev.map(route => 
          route.id === editingRoute.id ? { ...route, name: data.name } : route
        )
      );
      
      toast({
        title: "Route updated",
        description: `Route '${data.name}' has been updated successfully.`,
      });
    } else {
      // Create new route
      const newRoute: RouteType = {
        id: `${routes.length + 1}`, // In a real app, this would be generated by the backend
        name: data.name,
      };
      
      setRoutes(prev => [...prev, newRoute]);
      
      toast({
        title: "Route created",
        description: `Route '${data.name}' has been created successfully.`,
      });
    }
    
    setOpenDialog(false);
    setEditingRoute(null);
    form.reset();
  };
  
  const handleDelete = (id: string) => {
    setRoutes(prev => prev.filter(route => route.id !== id));
    
    toast({
      title: "Route deleted",
      description: "The route has been deleted successfully.",
      variant: "destructive",
    });
  };
  
  return (
    <MainLayout requiredRoles={['admin']}>
      <div className="space-y-6">
        <div className="flex justify-between items-center">
          <div>
            <h1 className="text-2xl font-bold mb-1">Routes Management</h1>
            <p className="text-gray-500">Manage delivery route areas</p>
          </div>
          <Dialog open={openDialog} onOpenChange={setOpenDialog}>
            <DialogTrigger asChild>
              <Button className="bg-blue-700 hover:bg-blue-800">
                <Plus className="h-4 w-4 mr-2" />
                Add Route
              </Button>
            </DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>{editingRoute ? 'Edit Route' : 'Add New Route'}</DialogTitle>
                <DialogDescription>
                  {editingRoute 
                    ? 'Update the route details below.' 
                    : 'Create a new route area for delivery planning.'}
                </DialogDescription>
              </DialogHeader>
              <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
                <FormField
                  control={form.control}
                  name="name"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Route Name</FormLabel>
                      <FormControl>
                        <Input placeholder="Enter route name" {...field} />
                      </FormControl>
                    </FormItem>
                  )}
                />
                <DialogFooter>
                  <Button 
                    type="button" 
                    variant="outline" 
                    onClick={() => {
                      setOpenDialog(false);
                      setEditingRoute(null);
                      form.reset();
                    }}
                  >
                    Cancel
                  </Button>
                  <Button 
                    type="submit" 
                    className="bg-blue-700 hover:bg-blue-800"
                  >
                    {editingRoute ? 'Update Route' : 'Add Route'}
                  </Button>
                </DialogFooter>
              </form>
            </DialogContent>
          </Dialog>
        </div>
        
        <Card>
          <CardHeader>
            <CardTitle>All Routes</CardTitle>
          </CardHeader>
          <CardContent>
            {loading ? (
              <div className="text-center py-6">Loading routes...</div>
            ) : (
              <>
                <div className="flex items-center mb-4">
                  <Input
                    placeholder="Search routes..."
                    className="max-w-sm"
                  />
                </div>
                
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>ID</TableHead>
                      <TableHead>Route Name</TableHead>
                      <TableHead className="text-right">Actions</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {routes.length === 0 ? (
                      <TableRow>
                        <TableCell colSpan={3} className="text-center py-6">
                          No routes found. Create your first route to get started.
                        </TableCell>
                      </TableRow>
                    ) : (
                      routes.map((route) => (
                        <TableRow key={route.id}>
                          <TableCell className="font-medium">{route.id}</TableCell>
                          <TableCell>{route.name}</TableCell>
                          <TableCell className="text-right">
                            <div className="flex justify-end space-x-2">
                              <Button
                                variant="outline"
                                size="sm"
                                onClick={() => {
                                  setEditingRoute(route);
                                  setOpenDialog(true);
                                }}
                              >
                                <Edit className="h-4 w-4" />
                              </Button>
                              <Button
                                variant="outline"
                                size="sm"
                                className="text-red-500 hover:text-red-600"
                                onClick={() => handleDelete(route.id)}
                              >
                                <Trash2 className="h-4 w-4" />
                              </Button>
                            </div>
                          </TableCell>
                        </TableRow>
                      ))
                    )}
                  </TableBody>
                </Table>
              </>
            )}
          </CardContent>
        </Card>
      </div>
    </MainLayout>
  );
}
